name: dagster-config-test

services:

  dagster-config-server:
    container_name: dagster-config-server
    image: kaupohumal/dagster-config-server:test
    pull_policy: always
    restart: on-failure
    environment:
      - GIT_REPO_URL=https://github.com/your-org/dagster-user-code.git
      - GIT_BRANCH=main
      - JOBS_SUBDIR=jobs
      - REPO_WORKDIR=/tmp/dagster-jobs-repo
      - GIT_AUTHOR_NAME=Dagster Config UI
      - GIT_AUTHOR_EMAIL=dagster-config-ui@local
      - GIT_USERNAME=git
      - GIT_TOKEN=${GIT_TOKEN}
    networks:
      - dagster-config
    ports:
      - "5000:5000"

  dagster-config-ui:
    container_name: dagster-config-ui
    image: kaupohumal/dagster-config-ui:test
    pull_policy: always
    restart: on-failure
    networks:
      - dagster-config
    ports:
      - "8090:80"
    depends_on:
      - dagster-config-server

networks:
  dagster-config:
    driver: bridge
    name: dagster_config