name: dagster-config-test

services:

  dagster-config-server:
    container_name: dagster-config-server
    image: kaupohumal/dagster-config-server:test
    pull_policy: always
    restart: on-failure
    environment:
      - JOBS_DIR=/app/jobs
      - DAGSTER_GRAPHQL_URL=http://docker_webserver:3000/graphql
      - HOME=/home/appuser
      - XDG_CACHE_HOME=/home/appuser/.cache
    volumes:
      - /mnt/dagster/jobs:/app/jobs
    networks:
      - dagster_network
    ports:
      - "5000:5000"

  dagster-config-ui:
    container_name: dagster-config-ui
    image: kaupohumal/dagster-config-ui:test
    pull_policy: always
    restart: on-failure
    networks:
      - dagster_network
    ports:
      - "8090:80"
    depends_on:
      - dagster-config-server

networks:
  dagster_network:
    driver: bridge
    name: dagster_network
    external: true